// <auto-generated />
using System;
using Guardian_API.Infrastructure.Data.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Guardian_API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Guardian_API.Domain.Entities.AerogeradorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AlturaMastro")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double>("CapacidadeMW")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<DateTime>("DataInstalacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("DiametroMotor")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int?>("FalhaEntityId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Garantia")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("ParqueEntityId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusOperacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tecnologia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("VelocidadeCorte")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.HasIndex("FalhaEntityId");

                    b.HasIndex("ParqueEntityId");

                    b.ToTable("TB_AEROGERADOR");
                });

            modelBuilder.Entity("Guardian_API.Domain.Entities.FalhaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EquipeManutencaoResponsavel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_FALHA");
                });

            modelBuilder.Entity("Guardian_API.Domain.Entities.LocalizacaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<double?>("Longitude")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_LOCALIZACAO");
                });

            modelBuilder.Entity("Guardian_API.Domain.Entities.ParqueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnoInauguracao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<double>("AreaKm")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int?>("LocalizacaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NumeroAerogeradores")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StatusOperacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tecnologia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("LocalizacaoId");

                    b.ToTable("TB_PARQUE");
                });

            modelBuilder.Entity("Guardian_API.Domain.Entities.TorreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInstalacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("LocalizacaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StatusOperacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("UltimaLeitura")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("LocalizacaoId");

                    b.ToTable("TB_TORRE");
                });

            modelBuilder.Entity("Guardian_API.Domain.Entities.AerogeradorEntity", b =>
                {
                    b.HasOne("Guardian_API.Domain.Entities.FalhaEntity", null)
                        .WithMany("Aerogeradores")
                        .HasForeignKey("FalhaEntityId");

                    b.HasOne("Guardian_API.Domain.Entities.ParqueEntity", null)
                        .WithMany("Aerogeradores")
                        .HasForeignKey("ParqueEntityId");
                });

            modelBuilder.Entity("Guardian_API.Domain.Entities.ParqueEntity", b =>
                {
                    b.HasOne("Guardian_API.Domain.Entities.LocalizacaoEntity", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoId");

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("Guardian_API.Domain.Entities.TorreEntity", b =>
                {
                    b.HasOne("Guardian_API.Domain.Entities.LocalizacaoEntity", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoId");

                    b.Navigation("Localizacao");
                });

            modelBuilder.Entity("Guardian_API.Domain.Entities.FalhaEntity", b =>
                {
                    b.Navigation("Aerogeradores");
                });

            modelBuilder.Entity("Guardian_API.Domain.Entities.ParqueEntity", b =>
                {
                    b.Navigation("Aerogeradores");
                });
#pragma warning restore 612, 618
        }
    }
}
